[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Specify the default Solidity version
solc = "0.8.20"

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    '@swap-router/contracts/=lib/swap-router-contracts/contracts/',
    '@uniswap/v3-staker/=lib/v3-staker',
    '@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/',
    '@uniswap/v3-core/contracts=lib/v3-core/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

--via-ir = true

[profile.permit2]
solc_version = "0.8.17"

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }

# [dependencies]
# uniswap-v3-core = { git = "https://github.com/Uniswap/v3-core.git" }
# uniswap-v3-periphery = { git = "https://github.com/Uniswap/v3-periphery.git" }
# forge-std = { git = "https://github.com/foundry-rs/forge-std" }
# openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v4.8.0" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
