[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# solc = "0.8.17"
--via-ir = true
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/contracts/=lib/v3-core/contracts/",
]
[profile.permit2]
solc_version = "0.8.17"


[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
# [dependencies]
# uniswap-v3-core = { git = "https://github.com/Uniswap/v3-core.git", branch = "main" }
# uniswap-v3-periphery = { git = "https://github.com/Uniswap/v3-periphery.git", branch = "main" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
