[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@uniswap/v2-periphery/=lib/v2-periphery/contracts/",
    "@uniswap/v2-core/=lib/v2-core/contracts/",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
